- key: userIP
  rate_limit:
    unit: hour
    requests_per_unit: 6
- key: userIP
  value: "172.28.1.10"
  rate_limit:
    unit: hour
    requests_per_unit: 5
- key: userIP
  value: "172.28.10.10"
  rate_limit:
    unit: hour
    requests_per_unit: 15

- key: userMac
  rate_limit:
    unit: minute
    requests_per_unit: 200
- key: userMac
  value: "AA:AA:AA:AA:AA:AA"
  rate_limit:
    unit: hour
    requests_per_unit: 5
- key: region
  value: Russia
  rate_limit:
    unit: hour
    requests_per_unit: 1
